### ISSUE TITLE
pivoting with Pandas, Ch3

### ISSUE THREAD

**Issue by OrielBanne** [stefmolin/Hands-On-Data-Analysis-with-Pandas#2]
pd.pivot(
    index=long_df.date, columns=long_df.datatype, values=long_df.temp_C
).head()

does not work on my station:
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-18380f508af5> in <module>
      1 pd.pivot(
----> 2     index=long_df.date, columns=long_df.datatype, values=long_df.temp_C
      3 ).head()

TypeError: pivot() missing 1 required positional argument: 'data'

**Comment by stefmolin** [comment]
I believe you are not using the correct version of pandas. For the book, we use 0.23.4 which as you can see from the [documentation](https://pandas.pydata.org/pandas-docs/version/0.23.4/generated/pandas.pivot.html) doesn't have `data` as an argument at all. This behavior was changed with the newest major release of pandas, so be sure to check the documentation if you are going to use a version not covered in the text.

**Comment by OrielBanne** [comment]
thanks!! I will change that for my practice environment!

best regards
Oriel
