### ISSUE TITLE
[FAIL] imblearn version 0.4.3 is required, but 0.6.2 installed.

### ISSUE THREAD

**Issue by nickanti** [stefmolin/Hands-On-Data-Analysis-with-Pandas#5]
Code should not generate fail message is newer version of module is installed.

**Comment by stefmolin** [comment]
If you choose to use a version other than what I wrote the examples on, then you are likely to find issues such as #2. For this reason, the checks will only succeed if you are running the same versions as the examples.  Be sure to use a virtual environment as covered in the text and you can have both versions installed for different purposes.
