### ISSUE TITLE
pkg-config is not installed error

### ISSUE THREAD

**Issue by bacheshrew** [stefmolin/Hands-On-Data-Analysis-with-Pandas#9]
### Required attestation
- [x] I have **completely and exactly** followed the virtual environment setup instructions from the book.
- [x] I have cloned either this repository or my fork of this repository so that I have all necessary files on my local machine.
- [x] I have checked that this issue has not already been reported or resolved [here](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas/issues?q=is%3Aissue).
- [x] I am aware that there is a [pre-built Binder environment](https://mybinder.org/v2/gh/stefmolin/binder-environments/1st_edition?urlpath=git-pull?repo=https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas) that I can use, but I want to install locally on my machine instead.

---

##### 1. Which OS are you using?
macOS Catalina (10.15.7) on a 2020 iMac/Intel i7 iMac

##### 2. Which Python version are you using?
v3.8.8

##### 3. Are you using `conda` or `venv`?
I used conda to setup an environment. I also tried venv but had the same error

---

### Commands run and their outputs
Please provide **all** of the commands you ran as well as the traceback:

*** NOTE: I named my env as 'book_env_c' to distinguosj it from attempts to use 'venv' ***

**Step 1 : I downloaded the ZIP from GitHub and extracted locally to my Mac**

**Step 2 : cd /Users/******/Code/Books/Hands-On-Data-Analysis-with-Pandas-master**
******@iMac2 Hands-On-Data-Analysis-with-Pandas-master % 

**Step 3 : %conda update conda**
Collecting package metadata (current_repodata.json): done
Solving environment: done

All requested packages already installed.

**Step 4 : %conda create --name book_env_c python=3.8.8**
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

Package Plan

  environment location: /Users/******/opt/anaconda3/envs/book_env_c

  added / updated specs:
    - python=3.8.8

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2022.4.26-hecd8cb5_0
  certifi            pkgs/main/osx-64::certifi-2022.6.15-py38hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-12.0.0-h2f01273_0
  libffi             pkgs/main/osx-64::libffi-3.3-hb1e8313_2
  ncurses            pkgs/main/osx-64::ncurses-6.3-hca72f7f_2
  openssl            pkgs/main/osx-64::openssl-1.1.1p-hca72f7f_0
  pip                pkgs/main/osx-64::pip-21.2.4-py38hecd8cb5_0
  python             pkgs/main/osx-64::python-3.8.8-h88f2d9e_5
  readline           pkgs/main/osx-64::readline-8.1.2-hca72f7f_1
  setuptools         pkgs/main/osx-64::setuptools-61.2.0-py38hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.38.5-h707629a_0
  tk                 pkgs/main/osx-64::tk-8.6.12-h5d9f67b_0
  wheel              pkgs/main/noarch::wheel-0.37.1-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-hca72f7f_1
  zlib               pkgs/main/osx-64::zlib-1.2.12-h4dc903c_2

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

To activate this environment, use

     $ conda activate book_env_c

To deactivate an active environment, use

     $ conda deactivate

**Step 5 : %conda activate book_env_c**
(book_env_c) ******@iMac2 Hands-On-Data-Analysis-with-Pandas-master % 

**Step 6 : %pip3 install -r requirements.txt**                                       
Collecting git+https://github.com/stefmolin/login-attempt-simulator.git@pandas_book (from -r requirements.txt (line 14))
  Cloning https://github.com/stefmolin/login-attempt-simulator.git (to revision pandas_book) to /private/var/folders/2v/2h45q9n92bn0v3mhqqv_8wxc0000gn/T/pip-req-build-qsa8c88k
  Running command git clone --filter=blob:none --quiet https://github.com/stefmolin/login-attempt-simulator.git /private/var/folders/2v/2h45q9n92bn0v3mhqqv_8wxc0000gn/T/pip-req-build-qsa8c88k
  Running command git checkout -q 4e386dc47d204de95c2d2b86efd9b9c55f60ee73
  Resolved https://github.com/stefmolin/login-attempt-simulator.git to commit 4e386dc47d204de95c2d2b86efd9b9c55f60ee73
  Preparing metadata (setup.py) ... done
Collecting git+https://github.com/stefmolin/ml-utils.git@pandas_book (from -r requirements.txt (line 15))
  Cloning https://github.com/stefmolin/ml-utils.git (to revision pandas_book) to /private/var/folders/2v/2h45q9n92bn0v3mhqqv_8wxc0000gn/T/pip-req-build-rxhb27mh
  Running command git clone --filter=blob:none --quiet https://github.com/stefmolin/ml-utils.git /private/var/folders/2v/2h45q9n92bn0v3mhqqv_8wxc0000gn/T/pip-req-build-rxhb27mh
  Running command git checkout -q 17934bedd6319957c698092d320ec23f4aa7e093
  Resolved https://github.com/stefmolin/ml-utils.git to commit 17934bedd6319957c698092d320ec23f4aa7e093
  Preparing metadata (setup.py) ... done
Collecting git+https://github.com/stefmolin/stock-analysis.git@pandas_book (from -r requirements.txt (line 16))
  Cloning https://github.com/stefmolin/stock-analysis.git (to revision pandas_book) to /private/var/folders/2v/2h45q9n92bn0v3mhqqv_8wxc0000gn/T/pip-req-build-nw0j48mx
  Running command git clone --filter=blob:none --quiet https://github.com/stefmolin/stock-analysis.git /private/var/folders/2v/2h45q9n92bn0v3mhqqv_8wxc0000gn/T/pip-req-build-nw0j48mx
  Running command git checkout -q 9eeb9d105eb84a8bea53423378d0a8a87e2e2206
  Resolved https://github.com/stefmolin/stock-analysis.git to commit 9eeb9d105eb84a8bea53423378d0a8a87e2e2206
  Preparing metadata (setup.py) ... done
Collecting graphviz==0.10.1
  Using cached graphviz-0.10.1-py2.py3-none-any.whl (16 kB)
Collecting imbalanced-learn==0.4.3
  Using cached imbalanced_learn-0.4.3-py3-none-any.whl (166 kB)
Collecting jupyterlab==0.35.6
  Using cached jupyterlab-0.35.6-py3-none-any.whl (14.8 MB)
Collecting matplotlib==3.0.3
  Using cached matplotlib-3.0.3.tar.gz (36.6 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      IMPORTANT WARNING:
          pkg-config is not installed.
          matplotlib may not be able to find some of its dependencies
      ============================================================================
      Edit setup.cfg to change the build options
      
      BUILDING MATPLOTLIB
                  matplotlib: yes [3.0.3]
                      python: yes [3.8.8 (default, Apr 13 2021, 12:59:45)  [Clang
                              10.0.0 ]]
                    platform: yes [darwin]
      
      REQUIRED DEPENDENCIES AND EXTENSIONS
                       numpy: yes [not found. pip may install it below.]
            install_requires: yes [handled by setuptools]
                      libagg: yes [pkg-config information for 'libagg' could not
                              be found. Using local copy.]
                    freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                              could not be found.  You may need to install the
                              development package.]
                         png: no  [pkg-config information for 'libpng' could not
                              be found.]
                       qhull: yes [pkg-config information for 'libqhull' could not
                              be found. Using local copy.]
      
      OPTIONAL SUBPACKAGES
                 sample_data: yes [installing]
                    toolkits: yes [installing]
                       tests: no  [skipping due to configuration]
              toolkits_tests: no  [skipping due to configuration]
      
      OPTIONAL BACKEND EXTENSIONS
                         agg: yes [installing]
                       tkagg: yes [installing; run-time loading from Python Tcl /
                              Tk]
                      macosx: yes [installing, darwin]
                   windowing: no  [Microsoft Windows only]
      
      OPTIONAL PACKAGE DATA
                        dlls: no  [skipping due to configuration]
      
      ============================================================================
                              * The following required packages can not be built:
                              * freetype, png
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

</details>

### Screenshots
Optionally, include any screenshots that will help diagnose the issue.

**Comment by stefmolin** [comment]
It looks like you are missing some system libraries that Matplotlib requires. Installing with `pip` won't handle those dependencies for you. I added an [`environment.yml` file](https://github.com/stefmolin/Hands-On-Data-Analysis-with-Pandas/blob/master/environment.yml) for you to use with `conda`, which should handle those system dependencies. Once you pull the changes, run the following command to create your environment:

```shell
conda env create --file environment.yml
```

**Comment by bacheshrew** [comment]
Thanks. I have managed to resolve this by specifying the same python version as used in the book when creating the virtual environment, ie: 

`conda create --name book_env_c python=3.6.4`

Thus, using 3.8.8 seemed to be the cause of the problem. The code may well work for 3.6.4+, but will need manual tweaking to resolve library issues.
